version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - services-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_aneka_zoo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anekazoodb
      MYSQL_USER: cPZKdNerJD
      MYSQL_PASSWORD: XMhRNy6m78
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - services-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_aneka_zoo
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - services-network

networks:
  services-network:
    driver: bridge

volumes:
  db_data:
